### ISSUE TITLE
Parametric and Polar Curves

### ISSUE THREAD

**Issue by sonnyk22** [maurizzzio/function-plot#12]
How can we graph Parametric and Polar Curves using Function-Plot? Is there a parameter that needs to be set to do this?

**Comment by maurizzzio** [comment]
It's not implemented yet

**Comment by maurizzzio** [comment]
implemented in e3b657f76dd2f905dc42869d806d22d6beb326db and 81ba1212744042c1e467a3955571030929e3607e

**Comment by sonnyk22** [comment]
awesome!  thank you
