### ISSUE TITLE
Get the plotted coordinates listing

### ISSUE THREAD

**Issue by sonnyk22** [maurizzzio/function-plot#13]
How can we get a listing for each plotted graphs? Both for a single or Multiple graphs?

**Comment by maurizzzio** [comment]
what do you mean by listing?

**Comment by sonnyk22** [comment]
For example, when I drag my mouse over a curve (ex: sin(8) ) on the graph; it shows me the coordinates.  is there a way that i get a listing of all those coordinates that has been plotted in the graph in the code?

**Comment by maurizzzio** [comment]
I think you can listen for the `tip:update` event, let me come up with an example

**Comment by sonnyk22** [comment]
I would great appreciated it if you could provide me with a small code example for this.

**Comment by maurizzzio** [comment]
```
var instance = functionPlot({
  target: '#playground',
  data: [
    { fn: 'x' },
    { fn: 'x^2' }
  ]
});

instance.on('tip:update', function (x, y, index) {
  // `index` is the index of the datum which has the tip
})

```

**Comment by sonnyk22** [comment]
thank you
