### ISSUE TITLE
Radians & Degrees

### ISSUE THREAD

**Issue by sonnyk22** [maurizzzio/function-plot#14]
Is there a way to graph Sin(8) in Radians, and Degrees.  I believe Function-Plot is currently defaulted to the Radians result; is my assumption correct?

**Comment by maurizzzio** [comment]
yes, it defaults to radians, can do `sin(8 * 180 / PI)` to transform degrees to radians but the trigonometric functions only work with radians

**Comment by sonnyk22** [comment]
nice!  when you said "can do sin(8 * PI / 180) to transform degrees to radians", did you mean "can do sin(8 * PI / 180) to transform radians to degrees"?

**Comment by maurizzzio** [comment]
mmm I think the transformation are:

- `deg = x * 180 / PI` when `x` is in radians (don't need to do this since the plotter works with radians)
- `rad = x * PI / 180` when `x` is in degrees (this is needed if an angle is expressed in degrees since function-plot works with radians)

**Comment by sonnyk22** [comment]
great! thanks...

**Comment by sonnyk22** [comment]
If its possible, it would be great if there was a option property for this feature.

**Comment by maurizzzio** [comment]
this is possible to do with math.js' sampler, e.g.

```
functionPlot({
  target: '#demo',
  data: [{
    fn: 'sin(90 deg)',
    graphOptions: {
      type: 'line',
      sampler: 'mathjs'
    }
  }]
});
```

**Comment by sonnyk22** [comment]
thank you
