### ISSUE TITLE
function-plot.js fle size

### ISSUE THREAD

**Issue by sonnyk22** [maurizzzio/function-plot#18]
I've noticed that the most current minified version of the function-plot.js file is 850k; but at the same time, the total code size in the /lib folder is under 50k.  Since it is minified and the comments have been removed, It is very hard to find out which other 3rd party vendor libraries has been included.  

1) Is it possible to let me know what other libraries are included in the function-plot.js?
2) are the site.js and index.js also needed to be included in my application (in index.html)?  I am sure the the answer is no to this question, but I had to ask to make sure.

**Comment by maurizzzio** [comment]
All the dependencies are listed in `package.json`, math.js codebase is quite huge, the problem is that there are a few functions that are just outside the scope of function-plot like `gamma` or `factorial`. I'll try to see if I can make math.js an optional dependency

**Comment by sonnyk22** [comment]
That would great.  Currently, in my application I have included math.js which is always being used, but the chart graphing using your library is used very little.  Having math.js included in function-plot.js for my scenario would be just of the large js file size issue.

**Comment by maurizzzio** [comment]
as of v1.7 math.js is no longer a dependency, make sure you include it before function-plot to use it instead of the bundled package that function-plot has

**Comment by sonnyk22** [comment]
fantastic!  thank you.
