### ISSUE TITLE
The event 'eval'

### ISSUE THREAD

**Issue by sonnyk22** [maurizzzio/function-plot#19]
This is a question is regarding #16.  It seems that this event only gets triggered when I click on the plotted chart with a slight move of the graph.  How can I get the same data returned without me physically clicking on the graph?  Or is there a way to trigger the 'eval' in the code?

**Comment by maurizzzio** [comment]
That's right, when you attach a listener to the instance the event was
already fired, I guess you can fire the "draw" event to make function plot
rebuild the graph e.g. `instance.fire('draw')`

**Comment by maurizzzio** [comment]
Sorry, it should be `instance.emit('draw')`

**Comment by sonnyk22** [comment]
awesome!  it worked!  thanks

**Comment by maurizzzio** [comment]
as of v1.9.4 the call has been replaced with `instance.draw()`
