### ISSUE TITLE
add support for plotting arrays as points or lines

### ISSUE THREAD

**Issue by whokilledtheelectricmonk** [maurizzzio/function-plot#2]
It would be cool to use the same viewport settings to plot arrays of points instead of functions, so that it could be integrated with something like an iPython notebook (e.g. compute the series in a more math-focused environment and use function-plot as a plotting output).

**Comment by maurizzzio** [comment]
I think that you can render a single point using a function although I don't like how it's done right now:

```javascript
// renders a point at (1, 2)
functionPlot({
  target: '#playground',
  data: [{
    fn: function (x) {
      return 2;
    },
    graphOptions: {
      type: 'scatter'
    },
    range: [1, 1]
  }]
})
```

Any suggestion on what the API should look like?

**Comment by maurizzzio** [comment]
as of https://github.com/maurizzzio/function-plot/releases/tag/v1.6.2 it's possible to render points/polylines, https://github.com/maurizzzio/function-plot/commit/3bee52c5b4a388dd711631260b0b23422b54f6fe

```javascript
functionPlot({
  target: '#points',
  data: [{
    points: [
      [1, 1],
      [2, 1],
      [2, 2],
      [1, 2],
      [1, 1]
    ],
    graphOptions: {
      type: 'scatter',
      sampler: 'mathjs'
    }
  }]
});
functionPlot({
  target: '#polyline',
  data: [{
    points: [
      [1, 1],
      [2, 1],
      [2, 2],
      [1, 2],
      [1, 1]
    ],
    graphOptions: {
      type: 'line',
      sampler: 'mathjs'
    }
  }]
});
```
