### ISSUE TITLE
Plotting options

### ISSUE THREAD

**Issue by sonnyk22** [maurizzzio/function-plot#20]
Are there options to initialize the graph for:

Polar and Parametric:
t- Minimum: 0 
t- Maximum: 2pi
t-Step (grid spacing) = pi/500 or 0.01

Function:
Step (grid spacing): 0.5 or 1.0 or 2.0, etc

**Comment by maurizzzio** [comment]
You have to combine both the `range` and `samples` parameters to achieve this e.g.

```javascript
functionPlot({
  target: '#parametric-circle',
  yDomain: [-1.897959183, 1.897959183],
  xDomain: [-3, 3],
  data: [{
    x: 'cos(t)',
    y: 'sin(t)',
    range: [0, 2 * Math.PI],
    samples: 100,
    parametric: true,
    graphOptions: {
      type: 'line'
    }
  }]
});
```

**Comment by sonnyk22** [comment]
The range worked great.  But, there is no way I can determine the correct value for the Steps (grid spacing) using the 'samples' property.  Is there a formula to find out the value that I need to set the 'samples' property to get T-Steps='PI/500' as an example?

**Comment by maurizzzio** [comment]
Well the first one is obvious if you have the number of samples you just set that in the `samples` options, if you have the distance between samples you have to measure the quantity of samples that is required to fill all the values of `range` e.g.

```
(range.hi - range.lo) / distance between samples
```

**Comment by sonnyk22** [comment]
I'll try it; hope I can make work.
