### ISSUE TITLE
Setting a color to each plotted line; also line thickness setting

### ISSUE THREAD

**Issue by sonnyk22** [maurizzzio/function-plot#21]
1) Lets say that we have to plot multiple charts in one graph, is there a way to assign a unique color to each plotted line?  Right now, a different color has been automatically defaulted to each line; how can we override this?
2) Is there a way to change a plotted line on the graph to be thicker line with difference line size setting?  Also, how to display in dashes if the end-user wants the plotted a line to be shown as a dash line?

**Comment by maurizzzio** [comment]
This kind of stuff is very customized and I think it's outside the scope of the library

1. you can easily change the color by changing the color of the `path` that represents a curve, there's a reference to the colors here `functionPlot.constants.COLORS` which can be overriden
2. you have to modify the path node that represents a curve e.g. https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Fills_and_Strokes

**Comment by sonnyk22** [comment]
great info.  thanks
