### ISSUE TITLE
Shift Key/Zoom box

### ISSUE THREAD

**Issue by sonnyk22** [maurizzzio/function-plot#27]
This is related to #17.  Let’s assume that we pass in such parameters in to the FP functions.

functionPlot({
  target: '#plugin-zoom-box',
  data: [{
    fn: 'x^2'
  }],
  plugins: [
    functionPlot.plugins.zoomBox({
      key: '<shift>'
    })
  ]
})

Then once we hold down the Shift key on the graph, then we can draw up a box to zoom in; this works great.

In addition to above, after the graph has been plotted, instead of holding down the Shift key, is there a way to tell the FB library (D3) to go into the Zoom mode, but by the code in button (or a menu) that is outside of the graph?  This can be important for Accessibility (handicap people, etc) that a lot of libraries out there are adding enhancements to.

**Comment by maurizzzio** [comment]
This is also known as programmatic zoom, I'll update the recipes section in the readme

**Comment by sonnyk22** [comment]
The added Programmatic Zoom functionality is great, but we have to know the x and y domains ahead of time.
var xDomain = [-3, 3]
var yDomain = [-1.897, 1.897]

Is there a way to tell the instance.programmaticZoom() function to only go into the Zoom mode without giving it  x and y domains values, and then let the end-user to draw the box using mouse?

**Comment by maurizzzio** [comment]
I see, I'll add a new option to the zoomBox plugin

**Comment by maurizzzio** [comment]
the plugin is now able to toggle its visible state as of v.1.9.1

```javascript
functionPlot({
  target: '#playground',
  data: [{
    fn: 'x^2'
  }],
  plugins: [
    functionPlot.plugins.zoomBox({
      toggle: true
    })
  ]
})
```

Now the key combination set for the plugin only updates the state of the mask instead of doing continuous checks on the keys that are pressed on mouseover, if you want to use a button to control this you can always modify the plugin itself e.g.

```javascript
var zoomBox = functionPlot.plugins.zoomBox({
  toggle: true
})
functionPlot({
  target: '#playground',
  data: [{
    fn: 'x^2'
  }],
  plugins: [zoomBox]
})
```

And on runtime you would do 

```javascript
zoomBox.visible(visible) // visible is a boolean value, true to show the mask, false to hide it
```

**Comment by sonnyk22** [comment]
The zoomBox.visible(visible) worked awesome!

One more question regarding this; is there an event that gets called once the zoomBox has completed drawing, so that I can call the zoomBox.visible(false) function to get out of Zoom Box mode?

**Comment by sonnyk22** [comment]
Is there an event that gets fired after the zoomBox has completed drawing?

**Comment by maurizzzio** [comment]
yep, as of v1.9.2 the following event will be fired

```javascript
```

**Comment by sonnyk22** [comment]
Awesome!  It worked great!  Thank you
