### ISSUE TITLE
Example with plotting functions parsed with math.js 

### ISSUE THREAD

**Issue by josdejong** [maurizzzio/function-plot#3]
Hi @maurizzzio , function-plot looks nice, thanks.

Maybe it's interesting to add an example (or use this on your demo page) with plotting functions parsed with [math.js](http://mathjs.org/). You can parse functions like:

```js
// parse a function
var fn = math.eval('fn(x) = x^2');

// plot the function
functionPlot({
  target: '#linear',
  data: [{fn: fn}]
});
```

**Comment by timelyportfolio** [comment]
:+1:

**Comment by maurizzzio** [comment]
sure @josdejong, thanks for the suggestion

**Comment by josdejong** [comment]
Thanks!

You could also create a text input where users can enter their own equation. People love to do that ;).

**Comment by josdejong** [comment]
Just for your information, I added a plot example to the examples of math.js using `function-plot`, see:

http://mathjs.org/examples/browser/plot.html.html
http://mathjs.org/examples/browser/plot.html (live example)

**Comment by maurizzzio** [comment]
awesome, thanks :D
