### ISSUE TITLE
Getting the left & right coordinates

### ISSUE THREAD

**Issue by sonnyk22** [maurizzzio/function-plot#30]
Using keys such as Control+Shift+mouse, is there a way to draw a box on the graph using mouse (similar to #27), and then when the mouse is released it triggers an event to provide us with the left & right ( and top & bottom) coordinates?

Example:
![diff](https://cloud.githubusercontent.com/assets/6744710/9262579/06c7bc0e-41e4-11e5-8737-6cca344a9796.png)

**Comment by maurizzzio** [comment]
This is possible through a plugin, refer to https://github.com/maurizzzio/function-plot/blob/master/lib/plugins/definite-integral.js#L37-L62 and the file itself on info on how to implement it, in the lines highlighted after the box is drawn `a` and `b` are the left and right coordiantes
