### ISSUE TITLE
Aspect Ratio

### ISSUE THREAD

**Issue by jbkunst** [maurizzzio/function-plot#33]
Hi Mauricio,

Thanks for this awesome library.

In a rectangular plot (let's said 800px  400px) how I can have both axis in the same scale? For example, if the plot is centered in (0, 0), show x between -10 and 10 and y between -5 and 5?

Regards

**Comment by maurizzzio** [comment]
Right now there's no way to tell function-plot to do that as an instruction however I've done that before  doing the following simple computations

Let's say that the dimensions of the graph are

```javascript
var width = 800
var height = 400
```

If we have the x scale limits

```javascript
var xMin = -10
var xMax = 10
var xDiff = xMax - xMin // 20
```

By [triangle similarity](http://www.mathopenref.com/similartrianglesparts.html) we have

```javascript
xDiff / width = yDiff / height
```

Solving for `yDiff`

`var yDiff = height * xDiff / width // 400 * 20 / 800 = 10`

So the limits of the yScale are `±yDiff / 2` from the plot's center

```javascript
function computeYScale (width, height, xScale) {
  var xDiff = xScale[1] - xScale[0]
  var yDiff = height * xDiff / width
  return [-yDiff / 2, yDiff / 2]
}

var width = 800
var height = 400
var xScale = [-10, 10]

functionPlot({
  width: width,
  height: height,
  xDomain: xScale,
  yDomain: computeYScale(width, height, xScale),
  
  target: '#demo',
  data: [{
    fn: 'x^2',
    derivative: {
      fn: '2x',
      updateOnMouseMove: true
    }
  }]
})
```

A similar logic can be applied to compute the `xScale` based on the `yScale`

**Comment by jbkunst** [comment]
Thanks again Mauricio!
