### ISSUE TITLE
functionPlot.constants.COLORS constants persistant

### ISSUE THREAD

**Issue by sonnyk22** [maurizzzio/function-plot#34]
The first time around, everything works great after setting my colors to the functionPlot.constants.COLORS, but it seems that the Function-Plot persists the first set of colors passed in even though the next time around when I set totally new colors to the functionPlot.constants.COLORS; even if I pass in the original colors predefined by the Function-Plot, it will not change them.  

When you get a free moment, would you be able to help me with this.

**Comment by maurizzzio** [comment]
thanks for the report, whenever you change `functionPlot.constants.COLORS` make sure to call `instance.update()` to redraw the graphs with the new colors

**Comment by sonnyk22** [comment]
I tried it, but it still persists the 1st set of colors that I have passed in.
Here is the code.  Would you verify if I have code it correctly.

![gr](https://cloud.githubusercontent.com/assets/6744710/9675197/510aee12-5288-11e5-9e2e-a2bf48fc01e5.png)

**Comment by maurizzzio** [comment]
sorry, it should be something like this

```javascript
var instance = functionPlot({
  target: '#demo',
  data: [{
    fn: 'x^2',
    derivative: {
      fn: '2x',
      updateOnMouseMove: true
    }
  }]
});
functionPlot.constants.COLORS = ['orange']
instance.draw()
```

**Comment by sonnyk22** [comment]
Unfortunately, I don't have a unique color names (ie: ['orange'])  for the colors that have been given to me.

Lets say, the below array has the original functionPlot.constants.COLORS values:

![original](https://cloud.githubusercontent.com/assets/6744710/9690544/f794472e-530a-11e5-8340-096a722db04b.png)

Below is the modified object array that I set to the functionPlot.constants.COLORS.  Please not that the red boxes are the changed values.  

![after](https://cloud.githubusercontent.com/assets/6744710/9690576/2b4000ae-530b-11e5-82e6-dc9b567cc293.png)

Is this the correct way of setting the new values to functionPlot.constants.COLORS?

**Comment by maurizzzio** [comment]
I see, well the following still works for me

```javascript
var instance = functionPlot({
  target: '#demo',
  data: [{
    fn: 'x^2',
    derivative: {
      fn: '2x',
      updateOnMouseMove: true
    }
  }, {
    fn: 'x'
  }]
});
functionPlot.globals.COLORS[0] = d3.hsl('orange')
functionPlot.globals.COLORS[1] = 'green'
console.log(functionPlot.globals.COLORS)
instance.draw()
```

Note that as of v1.11.x `functionPlot.constants` was renamed to `functionPlot.globals`

**Comment by sonnyk22** [comment]
It worked great; thank you
