### ISSUE TITLE
Graph plotting outside of viewing window / unable to find graph of function

### ISSUE THREAD

**Issue by ThunderHeavyIndustries** [maurizzzio/function-plot#39]
I've got a function that's using really large numbers. I know it's graphing because the mouseover is showing values. But I can't locate the lines on the graph, even when I go to where they should be. Zooming out far enough seems to make the drawing of the lines dodgy as well. Is there a way to recenter the viewing window over some range of a function?

ie: the graph loads and shows  x values from [-5,5] and y from [-5,5] but the function is around say x[0,5] and y[100,200]. The actual numbers I'm dealing with are much larger but the idea is the same.

**Comment by maurizzzio** [comment]
Thanks for the report!

For the viewport problem you can use the `xDomain` and `yDomain` options, for the dodgy lines I need the function you want to plot, I suspect the problem is in the `<path>` tag that renders the  line

**Comment by ThunderHeavyIndustries** [comment]
An example of one of these functions would be:

y = ((1.983*10^5^2)*6.700*(1-(6.700/x)))/(( 1-1.652*(1-(6.700/x)))^2)

I've tried setting the domains but to it hasn't worked out for me. I think it's the combo of the size, and the zoom not playing nice.

**Comment by maurizzzio** [comment]
The function is weird indeed, it makes a jump from `+a huge` number to `-a huge number`, anyway that dramatic change is being captured by interval arithmetic and is now clamped to the viewport

v1.12.3

**Comment by ThunderHeavyIndustries** [comment]
Awesome, thanks so much. I'll check it out on Monday and let you know how it goes.

**Comment by ThunderHeavyIndustries** [comment]
And there it is! Thank you so much, looks great!
