### ISSUE TITLE
Plot has very thick axes

### ISSUE THREAD

**Issue by josdejong** [maurizzzio/function-plot#4]
I tried to create a simple example with math.js + function-plot, but in this example the axis of the plot are black and have a width of about 10px.

Here is a jsbin demonstrating the issue: http://jsbin.com/qasoze/edit?html,output

What am I overlooking?

**Comment by maurizzzio** [comment]
hi, indeed it was a problem on the initial release but is now fixed on 0.4.0

http://jsbin.com/voqixogixu/1/edit?html,output

**Comment by josdejong** [comment]
Ah, that looks better. Thanks for the fast fix!
