### ISSUE TITLE
Adding a title moves the SVG and the axes are lost

### ISSUE THREAD

**Issue by amlwwalker** [maurizzzio/function-plot#41]
When you have a chart without a title:
![image](https://cloud.githubusercontent.com/assets/2920180/10412494/6ffb4f74-6f7f-11e5-8ae5-dbfb3394260d.png)

the axes and axes labels are "good". If you add a title, the chart shifts down and you lose visual on the axes and x axis label:

![image](https://cloud.githubusercontent.com/assets/2920180/10412498/8eabe1d6-6f7f-11e5-82a3-c893c417ffba.png)

**Comment by maurizzzio** [comment]
Thanks for the report!

**Comment by maurizzzio** [comment]
should be fixed on v1.12.4
