### ISSUE TITLE
Custom function

### ISSUE THREAD

**Issue by WG-** [maurizzzio/function-plot#45]
Is it possible to also create a function plot with a custom function which is not included in Math.js or the Numeric Interval library?

functionPlot({
  title: 'y = x * x',
  target: '#quadratic-with-options',
  width: 580,
  height: 400,
  disableZoom: true,
  xLabel: 'x - axis',
  yLabel: 'y - axis',
  data: [{
    fn: 'f(x)^2'
  }]
})

Where f(x) is defined as

function f(x) { return x; }

as an example.

**Comment by maurizzzio** [comment]
thanks for the suggestion! actually function-plot did this on its initial release but due to weird plots shown I switched to interval arithmetic, it could be a nice feature indeed

**Comment by maurizzzio** [comment]
Implemented on v1.14.0 1b6aa6856df006d0807d9c1ef8572343121069b2

**Comment by maurizzzio** [comment]
Make sure you read the last example in http://maurizzzio.github.io/function-plot/
