### ISSUE TITLE
Logarithmic axis

### ISSUE THREAD

**Issue by WG-** [maurizzzio/function-plot#46]
Is it possible to select a axis to be logarithmic instead of linear?

**Comment by maurizzzio** [comment]
Not yet, it'd be kinda hard to evaluate a function with the interval library but it's a good idea

**Comment by WG-** [comment]
Is it possible to maybe already implement this for a different sampler, i.e., math.js? It would really help me since I want to create a bode plot; https://en.wikipedia.org/wiki/Bode_plot

**Comment by maurizzzio** [comment]
Check out the logarithmic example on the main page, thanks for the idea :+1: 

v1.16.1

**Comment by WG-** [comment]
@maurizzzio Very nice! Small detail is it possible to show only powers of 10? so 0.1, 1, 10? Not 0.1,0.2,0.3,...,1,2,3,...,10

**Comment by maurizzzio** [comment]
the scale is fully controlled by d3, if you want to update some options have a look at https://github.com/d3/d3-scale and https://github.com/mbostock/d3/wiki/SVG-Axes, inside function plot the scale and axis is available through `instance.meta`

```js
var instance = functionPlot({ ... })
instance.meta.xScale
// and
instance.meta.xAxis
```

It seems from the documentation that https://github.com/mbostock/d3/wiki/SVG-Axes#tickValues should do the trick therefore you should do something like this

```js
instance.meta.xAxis
  .tickValues([ ... ])
```

**Comment by WG-** [comment]
Ah okay great! Didn't knew that was possible!
