### ISSUE TITLE
Link axis separately

### ISSUE THREAD

**Issue by WG-** [maurizzzio/function-plot#50]
For some cases it maybe more useful to link axis separately. Maybe you only want the x-axis to be linked or the y-axis. But not both, as the current implementation.

**Comment by maurizzzio** [comment]
mmm I didn't get it, is it related to the zoom operation being operated on both axes?

**Comment by WG-** [comment]
Yes. As an example, you have two plots which you link to each other. You set the x-domain of plot 1 and 2 as (-10,0) and (0,10), respectively. The y domain you set for both as (0,5). Now when you zoom or pan in plot 1 the x-domain of plot 2 is changed to (-10,0). There are numerous cases where this behavoir is unwanted.

**Comment by WG-** [comment]
In additiion, it would also be nice to set an max and min domain, i.e., you cannot zoom in or out further then the min and max.

**Comment by maurizzzio** [comment]
I see, I think this is a bug since example that you mention is what I'd expect however the new zoom bounds are being dispatched to all the linked plots, dispatching the zoom diff should fix it

**Comment by maurizzzio** [comment]
the max and min can be set through `instance.zoomBehavior.scaleExtent` see https://github.com/mbostock/d3/wiki/Zoom-Behavior#scaleExtent

v1.16.2
