### ISSUE TITLE
Axis range number showing -0.0

### ISSUE THREAD

**Issue by sonnyk22** [maurizzzio/function-plot#51]
When zooming-in, the Axis Range numbering is showing -0.0, as shown below.

![calc1](https://cloud.githubusercontent.com/assets/6744710/12184347/c05cdfe0-b562-11e5-9746-91ac9aab4f22.png)

**Comment by maurizzzio** [comment]
[`d3.scale.linear`] computes the ticks values in that way, I'm quite sure the number is something like -0.000000038923472 but due to rounding it becomes -0.0, I don't want to add special code for this special case on function-plot
