### ISSUE TITLE
Wrong mouse coordinates if parent is scaled

### ISSUE THREAD

**Issue by rajgoel** [maurizzzio/function-plot#53]
I'm using reveal.js (http://lab.hakim.se/reveal-js/) to show function plots (see http://courses.telematique.eu/reveal.js-plugins/anything-demo.html#/2 and https://github.com/rajgoel/reveal.js-plugins/tree/master/anything#function-plotjs). Unfortunately, the function plot appears to be confused by the scaling of reveal.js. This causes the tip to be at the wrong coordinates.

Below screenshot illustrates the problem. Unfortunately, it does not capture the mousepointer, so I just drew a red circle. The tip is at the x-coordinate -6 whereas the mouse-pointer is at x-coordinate +6.
![screenshot from 2016-01-25 15 47 15](https://cloud.githubusercontent.com/assets/4448455/12554187/9d3421f0-c37b-11e5-9adf-7735005f6d66.png)

I have managed to make a minimal example having the same problem:

```html
<!DOCTYPE html>
<html>
<head lang="en">
	<meta charset="UTF-8">
	<title>demo</title>
</head>
<body>

<div style="transform: scale(1.5);">
	<span id="sinus"></span>
</div>

  <script src="js/vendor/jquery-1.11.2.min.js"></script>
  <script src="js/vendor/d3.js"></script>
  <script src="js/function-plot.js"></script>
  <!--<script src="js/site.js"></script>-->
  <script>
var a = functionPlot({
  target: '#sinus',
  width: 800,
  height: 400,
  xAxis: {domain: [-10, 10]},
  data: [{ fn: 'sin(x)' }]
})
  </script>
</body>
</html>
```

Obviously, the cause of the problem is the scaling: ```<div style="transform: scale(1.5);">```.

The problem is similar to this one: http://stackoverflow.com/questions/20339047/reveal-js-with-highcharts. Is there any workaround (e.g. like the one proposed here http://stackoverflow.com/questions/20339047/reveal-js-with-highcharts/20348347#20348347) or can this be fixed in the function-plot library?

**Comment by maurizzzio** [comment]
@rajgoel sorry for my late reply, I've been sick the last month and I'm finally recovering

Thanks for the report and investigation! I've actually reproduced this one and the problem is the way `d3.mouse` works, working on a workaround...

**Comment by maurizzzio** [comment]
Sadly I couldn't solve it completely, there's a magic transformation done on scale on `d3.mouse` which fails to be correct when the container is scaled (as it's on this bug),  one would think that doing a simple subtraction or scale operation on the scaled graph would work but apparently there's a magic number which I didn't manage to compute

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>

<div style="position: absolute; top: 0; left: 0; right: 0; bottom: 0; width: 900px; height: 700px; margin: auto; zoom: 1.3">
  <div style="margin: 0 auto; width: 800px" id="sinus"></div>
</div>
  
  <script src="js/vendor/d3.js"></script>
  <script src="js/function-plot.js"></script>
  
<script>
var instance = functionPlot({
  target: '#sinus',
  width: 800,
  height: 400,
  xAxis: {domain: [-10, 10]},
  data: [{ fn: 'sin(x)' }]
})
instance.on('before:mousemove', function (coordinates) {
  var draggable = instance.draggable.node()
  var target = instance.root.node().parentNode

  // find the ancestors of target which scale their content
  // for now assume that it's just the first ancestor of target
  var container = target.parentNode
  if (container.style.zoom) {
    var scale = parseFloat(container.style.zoom)
    var scaledWidth = instance.meta.width * scale
    var scaledWidthDiff = scaledWidth - instance.meta.width
    var mouse = d3.mouse(draggable)

    // varies depending on the scale factor, it's not linear
    var magicNumber = 120

    var nx = mouse[0] - magicNumber
    nx -= (nx / scaledWidth) * scaledWidthDiff
    coordinates.x = instance.meta.xScale.invert(nx)
  }
})
</script>

</body>
</html>
```

The experiment can be found at http://maurizzzio.github.io/function-plot/scale.html

**Comment by rajgoel** [comment]
Hi Mauricio,

thanks for having a look at it. It appears that for some reason  ```coordinates.x``` has a different value for Chrome and Firefox (i.e. shifted by a fix value).

The below code works for me on Firefox for different scaling factors, but not on Chrome:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>

<div style="transform: scale(1.5);">
  <div style="margin: 0 auto; width: 800px" id="sinus"></div>
</div>

  <script src="http://maurizzzio.github.io/function-plot/js/vendor/d3.js"></script>
  <script src="http://maurizzzio.github.io/function-plot/js/function-plot.js"></script>

<script>
var instance = functionPlot({
  target: '#sinus',
  width: 800,
  height: 400,
  xAxis: {domain: [-10, 10]},
  data: [{ fn: 'sin(x)' }]
});
instance.on('before:mousemove', function (coordinates) {
  var target = instance.root.node().parentNode;
document.title = coordinates.x; // use page title to monitor mouse coordinates
  coordinates.x = coordinates.x * target.offsetWidth  / target.getBoundingClientRect().width;
});
</script>

</body>
</html>
```
Note that you don't need to obtain the scale value from the ancestor. It can be computed from ```target.offsetWidth```  and ```target.getBoundingClientRect().width```.

**Comment by rajgoel** [comment]
Finally, I found a workaround for the problem. It appears that the following code also works in Chrome.

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>

<div style="transform: scale(1.5);">
  <div style="margin: 0 auto; width: 600px" id="sinus"></div>
</div>

  <script src="d3.min.js"></script>
  <script src="function-plot.js"></script>

<script>
var instance = functionPlot({
  target: '#sinus',
  width: 600,
  height: 400,
  xAxis: {domain: [-10, 10]},
  data: [{ fn: 'sin(x)' }]
});

var scaleX = 1; 
var scaleY = 1; 

(function(d3) {
 function d3_eventSource() {
  var e = d3.event, s;
  while (s = e.sourceEvent) e = s;
  return e;
 }

 d3.mouse = function(container) {
  return d3_mousePoint(container, d3_eventSource());
 };

 function d3_mousePoint(container, e) {
  var rect = container.getBoundingClientRect();
  return [ (e.clientX - rect.left - container.clientLeft)*scaleX, (e.clientY - rect.top - container.clientTop)*scaleY];
 };

})(d3);

instance.on('before:mousemove', function (coordinates) {
    var target = instance.root.node().parentNode;
    scaleX = target.offsetWidth  / target.getBoundingClientRect().width;
    scaleY = target.offsetHeight  / target.getBoundingClientRect().height;
});
</script>

</body>
</html>
```

**Comment by maurizzzio** [comment]
Awesome @rajgoel, initially I thought this required an override on the scale since `d3.mouse` seemed to return the correct result, boy I was wrong, really nice solution 👍
