### ISSUE TITLE
Plotting functions of x to the power of a float/decimal

### ISSUE THREAD

**Issue by Kallaway** [maurizzzio/function-plot#57]
Hi @maurizzzio ! Thank you so much for all your previous help, I really appreciate it! Another issue I've come across is when I try to plot a function of f(x) = x^ 1.5  - for example. Then it doesn't work and tells me to use nth-root, for example: "nthRoot(x, 3) ^ 2". Then there is an error of "Error: Root must be odd when a is negative". Is there a native way to build such functions (when "the power of" is not a whole number) or is there a workaround (such as nthRoot mentioned above) because I haven't had success with that yet. (I am not sure how to tell function plot to only use positive values of x)

Thank you so much in advance!

**Comment by maurizzzio** [comment]
`nthRoot(x, 3) ^ 2` works for me, you can also use conditionals on the `fn` string e.g.

```js
functionPlot({
  target: '#demo',
  data: [{
    fn: 'x > 0 ? nthRoot(x, 3) : EMPTY'
  }]
});
```

`EMPTY` is defined on the interval arithmetic package btw, conditional expression are parsed with https://www.npmjs.com/package/mr-parser

**Comment by Kallaway** [comment]
Hi @maurizzzio I still have the issue - when I do either: `fn: 'x > 0 ? nthRoot(x, 3) : EMPTY'` or `nthRoot(x, 3) ^ 2`, the graph just shows a line parallel to the x-axis. Maybe I am forgetting some other setting of the graph? If possible, could you share the whole object that you are giving to the functionPlot() function that works for you in this case? Thank you so much in advance for your help!

**Comment by maurizzzio** [comment]
I've plotted both graphs and the results are correct for all values, remember that `nthRoot(x,3)` is `x^(1/3)` and `nthRoot(x, 3) ^ 2` is `x^(2/3)`, the parallel line you might be looking at occurs when the zoom 

[demo](http://jsbin.com/wocozod/edit?html,js,output)

**Comment by Kallaway** [comment]
Thank you! I was able to fix it before you've replied by adding: `graphType: 'polyline'` , but I think the only reason I had to add it was because I've set that to something else before, and had to override it when I had to plot the graph later on. Special thanks for the demo!
