### ISSUE TITLE
Conversion between SVG coordinates and logical coordinates

### ISSUE THREAD

**Issue by ischurov** [maurizzzio/function-plot#59]
I'd like to add svg element to the graph made with function plot like this:

```javascript
$(window).load(function(){
functionPlot({
  target: '#demo',
  data: [{
    fn: 'sin(10*(-cos(x) + y^2/2-1))',
    fnType: 'implicit'}]
});
var svg = d3.select("#demo").selectAll("svg");
svg.append('circle').attr("cx", 125).attr("cy", 125).attr("r", 5).style("fill", "purple");
});
```

This code work, but coordinates of the circle are in SVG coordinate system, and I'd like to place the circle to the point with the coordinate known in our logical coordinate system (e.g. to place it to the origin or to point (1, 2)). To do so, I have to know how these coordinates are converted to each other. Are there any ways to do it?

Also is it possible to make a hook for 'onclick' event and get logical coordinates of the mouse pointer (e.g. to place my circle to this point)?

See also [this question](http://stackoverflow.com/questions/36066080/optimize-pendulum-animation-javascript).

**Comment by maurizzzio** [comment]
The problem with that approach is that functionPlot doesn't know about the circle you just added which means that you'd have to manually update its position on the canvas, a better approach is to create a new object in `data` to save the points you want, the configuration to add points is

```js
functionPlot({
  target: '#points',
  data: [{
    points: [
      [1, 1],
      [2, 1],
      [2, 2],
      [1, 2],
      [1, 1]
    ],
    fnType: 'points',
    graphType: 'scatter'
  }]
})
```

The canvas only fires the `double click` event however simulating the `click` event is quite simple, see the following example which adds points on click

[demo](http://jsbin.com/movelijebe/edit?html,js,output)

**Comment by ischurov** [comment]
@maurizzzio thanks for the fast response. Actually, I tried the approach you proposed but finally decided to consider another approach with "independent" circle due to the following reasons:

1. There are no ways to control the size of a circle plotted by `graphType: 'scatter'` due to [this issue](https://github.com/maurizzzio/function-plot/issues/28#issuecomment-182211329) and default value is too small for me.
2. I was going to 'freeze' the plot (disable zooming, etc.) and get almost static picture (I do not need zoom/pan features).
3. Finally (and most important), I'd like to animate the position of the circle and I'm afraid that if this circle would be part of functionPlot graph (as in scatter solution you proposed), every time I'll update its position during animation it will redraw the whole functionPlot graph — with obvious performance drawbacks. (See the question mentioned in my first comment for details.)

I'm not sure, if my considerations are correct for issue 3 from the list above. If I'm wrong here (i.e. update of the position of one point will not lead to redrawing of the whole image and the animation can be made smooth), I'll get back to this approach. (Actually, it is possible to replace `scatter` point with some other curve to overcome issue 1).

Thanks for the example of 'onclick' hack.

**Comment by maurizzzio** [comment]
Your assumptions are correct and thanks for the suggestion of adding the `onclick` event, I'll add this in a future relase

**Comment by ischurov** [comment]
Thanks, but if I'm right with issue 3, I'm still interested in the initial question on the conversion between SVG coordinates and functionPlot coordinates. Is it true that there are no such converters (like `d3.scale` instance) available now?

**Comment by maurizzzio** [comment]
Assuming that

```javascript
var instance = functionPlot({ ... })
var xScale = instance.meta.xScale
var yScale = instance.meta.yScale
```

The following code converts a point expressed in canvas coordinates (expressed relative to the nested `<g class="content">` element created by function plot) to logical coordinates

```javascript
var point = d3.mouse(instance.root.select('rect.zoom-and-drag').node())
var x = xScale.invert(mouse[0])
var y = xScale.invert(mouse[1])
```

From logical coordinates to the canvas coordinates

```javascript
var x = xScale(point.x)
var y = yScale(point.y)
```

With that in mind I guess your animation will look like this demo

[demo](http://jsbin.com/yexeya/edit?html,js,output)

**Comment by ischurov** [comment]
Amazing! Thanks a lot! Would you mind if I ask you to copy this answer to my [stackoverflow question](http://stackoverflow.com/questions/36066080/optimize-pendulum-animation-javascript), so I'll be able to accept it and credit you with some SO reputation points?
