### ISSUE TITLE
Adding IDs to plotted functions: Feature request?

### ISSUE THREAD

**Issue by Kallaway** [maurizzzio/function-plot#60]
Hi @maurizzzio . I've been working with this library for a while now, and it is absolutely amazing and well-coded. 

As I've been plotting the graphs, I've noticed that there are no ids assigned to the functions that are plotted, only classes: e.g. line-0, line-1, etc. This works if the tool just plots graphs, but the way I am using it involves adding and removing graphs (for example, placing dots, and then plotting a function based on the dots the user plotted). Sometimes, one of the functions gets removed, and then when the graph gets redrawn, let's say the function that was third becomes second, and the styles I've applied to the class line-1 start working with the line that used to be third.

Is there a way to add ids to functions that are plotted, and if not, I think there should be a way because it would make it much easier to extend the tool for new uses (such as adding interactivity, plotting and manipulating multiple shapes - rectangles, triangles, etc.) That way we could just simply add the id to a function and style it in the same way no matter what other functions get added/removed to/from the SVG.

**Comment by maurizzzio** [comment]
As of v1.16.4 you can do the following

```javascript
functionPlot({
  data: [{
    fn: 'x^2',
    attr: {
      id: 'id',
      stroke: 'red'
    }
  }]
})
```

**Comment by Kallaway** [comment]
There is a small issue with this: for example, when I change the graph's `stroke-width`, it changes the graph's color correctly, but the colors of inner-tip (both the center circle and the coordinates) and top-right-legend still have the color that is dictated by their number (first, second, etc.) as defaults: first one shows in blue, second in red, etc. I am attaching screenshot. 

![screen shot 2016-03-24 at 9 21 45 am](https://cloud.githubusercontent.com/assets/8016212/14018097/39c23e7c-f1a2-11e5-9224-d7f41772e9de.png)

Thank you so much for implementing this yesterday, it made my day! :)
