### ISSUE TITLE
Question regarding e^x - x 

### ISSUE THREAD

**Issue by sonnyk22** [maurizzzio/function-plot#63]
Is there a special syntax that I'll need to pass into Function-Plot (FP) when there is `e` in the equation?  For example:

Equation: `e^x - x `
FP error:  `Error: unexpected character undefined at index 8`

Equation: `3e^(3x) - (3x^2)`
FP error:  `Error: undefined at index 2`

**Comment by sorawee** [comment]
Use exp function instead of e^

**Comment by sonnyk22** [comment]
Thank you!
