### ISSUE TITLE
Possible incorrect representation of a log function

### ISSUE THREAD

**Issue by Kallaway** [maurizzzio/function-plot#64]
Hi @maurizzzio ,

I've encountered a weird issue when trying to plot the function below. For some reason, it seems like the syntax of the expression is being read in the wrong way.

The function I was trying to plot was this: f(x) = 2 * log((4-x) / 8).

The example value of X that I've used was 2. When X is 2, function plot library gives me the Y value of is around -2.8.

To check, I've used this online tool: https://www.desmos.com/calculator - and when I input the same function there, the graph is different, and, given X = 2, the value of Y there is around -1.2.

Could you please tell me if this is an issue, or is there something I am doing wrong? Is there a possibility of using another syntax reader, or is it me going too far? You will find my simple code below:

```
functionPlot({
  target: '#demo',
  data: [{
    fn: '2*log((4-x)/8)'
  }]
});
```

Thank you so much in advance for your help and thank you for all the help you've already given me before!

**Comment by maurizzzio** [comment]
`log` is the natural logarithm (base `e`), use `log10` instead

**Comment by Kallaway** [comment]
Thank you so much! We literally figured out what it was doing about 3 minutes ago! This worked!
