### ISSUE TITLE
Why isn't logistics function drawn?

### ISSUE THREAD

**Issue by nicroto** [maurizzzio/function-plot#75]
```
functionPlot( {
    target: "#diiGraph",
    xAxis: {
        domain: [0, 10]
    },
    yAxis: {
        domain: [0, 2]
    },
    disableZoom: true,
    data: [
        { fn: "x", color: "pink" },
        { fn: "x * x * x" },
        { fn: "1 / (1 + 2.718^((-1) * (x - 6)))", color: "green"}
    ]
} );
```

The first 2 are drawn, but the 3rd you can follow the line with cursor (values are displayed), but the actual curve is invisible.

System: Chrome 52.0.2743.116 (64-bit) (this is latest official), OS X 10.11.5

Awesome project, btw.

Cheers!

**Comment by maurizzzio** [comment]
There are some corner cases in the evaluation of `2.718^((-1) * (x - 6))` that I haven't been able to solve yet (weird cases of interval power), please use this instead:

```js
functionPlot( {
    target: "#diiGraph",
    xAxis: {
        domain: [0, 10]
    },
    yAxis: {
        domain: [0, 2]
    },
    disableZoom: true,
    data: [
        { fn: "x", color: "pink" },
        { fn: "x * x * x" },
        { fn: "1 / (1 + 2.718^((-1) * (x - 6)))", color: "green", graphType: 'polyline'}
    ]
} );
```

Please have a look at the `Advanced: sampler` example on the main page for an explanation of solution

**Comment by nicroto** [comment]
Awesome!
Thanks for the lightning-fast response.
