### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by pavelkabanov** [maurizzzio/function-plot#80]
How to use this library?
I have this code
`<script src="https://d3js.org/d3.v3.min.js"></script>`
`<script src="https://wzrd.in/standalone/function-plot@1.17.0"></script>`
`<script>
functionPlot({
  target: '#quadratic',
  data: [{
    fn: 'x^2'
  }]
})
</script>`
`<div id="quadratic">
</div>`
But there is no graph...

**Comment by maurizzzio** [comment]
Define your <div id="quadratic"> tag before the script that invokes
function plot

**Comment by pavelkabanov** [comment]
There is full code, that doesn't work:
`<!DOCTYPE html>`
`<html>`
`<head>`
`<meta charset="utf-8">`
`<title></title>`
`<script src="https://d3js.org/d3.v3.min.js"></script>`
`<script src="https://wzrd.in/standalone/function-plot@1.17.0"></script>`
`</head>`
`<body>`
`<div id="quadratic">`
`</div>`
`<script>
functionPlot({
  target: '#quadratic',
  data: [{
    fn: 'x^2'
  }]
});
</script>`
`</body>`
`</html>`

**Comment by maurizzzio** [comment]
It's working https://codepen.io/anon/pen/zKEmqd

**Comment by pavelkabanov** [comment]
Well, I solve this problem. This is because my old computer doesn't support WebGL.
