### ISSUE TITLE
Plotting vertical line not as an annotation

### ISSUE THREAD

**Issue by anisbi** [maurizzzio/function-plot#86]
Hello,
based on the approach given in [mathjs.org function-plot example](http://mathjs.org/examples/browser/plot.html.html), is there a way to allow the user to plot vertical lines? For example inputting `x=5`?

p.s. Using this library for my graduation project <3

**Comment by maurizzzio** [comment]
Sure, you can either:

1) Plot an implicit equation of the form `Ax + By + C = 0` e.g. `-x + 5 = 0`

```js
functionPlot({
  target: '#demo',
  data: [{
    fn: '5 - x',
    fnType: 'implicit'
  }]
});
```

2) Use a really high step for a linear equation in the form `y = mx + b` e.g. `y = m * x - 5 * m` where  `m` is a really huge number

```js
functionPlot({
  target: '#demo',
  data: [{
    fn: 'm * x - 5 * m',
    scope: { m: 10000 }
  }]
});
```
