### ISSUE TITLE
Domain option not working

### ISSUE THREAD

**Issue by varunagrawal** [maurizzzio/function-plot#88]
I used the example on the [Math.js page](http://mathjs.org/examples/browser/plot.html.html) and when I try to update the equation, it works great. However, when I set the domain to [0, 8] it does not update.

Below is my JS:

```javascript
  function draw() {
    try {
      functionPlot({
        target: '#plot',
        xAxis: {domain: [0, 7]},
        data: [{
          fn: document.getElementById('eq').value,
          sampler: 'builtIn',  // this will make function-plot use the evaluator of math.js
          graphType: 'polyline'
        }]
      });
    }
    catch (err) {
      console.log(err);
      alert(err);
    }
  }

  document.getElementById('form').onsubmit = function (event) {
    event.preventDefault();
    draw();
  };

  draw();
```

**Comment by maurizzzio** [comment]
Are you using the latest version of function plot? it's working on 1.17.3

http://jsbin.com/heqicozaxo/edit?html,js,output

**Comment by varunagrawal** [comment]
I am not. I am using 1.14. Let me try it out real quick.

**Comment by varunagrawal** [comment]
Works! Sorry about that, though great work, I am really enjoying this library.
